services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - .git/
            - node_modules/
            - "**/*.log"
    ports:
      - "1323:1323"
    pull_policy: build
    environment:
      DB_URI: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 5

  jaeger:
    image: jaegertracing/jaeger:latest
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "16687:16687"
      - "4317:4317"
      - "4318:4318"


volumes:
  postgres_data: